In [ ]:
import numpy as np
from Lo_Gobang_151.submission import *

In [ ]:


_x = [
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    ]

In [ ]:

_x = np.array(_x)
observations = {'state_map': _x, 'chess_player_idx': 1}

In [139]:

res = my_controller(observations, 1)
x = np.argmax(res[0])
y = np.argmax(res[1])
_x[x, y] = 2
print(x, y)
print(_x)

9 2
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 2 1 0 0 0 2]
 [0 0 0 0 0 2 1 2 2 2 1 0 0 1 0]
 [0 0 0 0 2 0 1 1 2 1 0 0 2 0 0]
 [0 0 0 0 2 1 2 2 2 1 0 2 1 2 0]
 [0 0 0 0 0 0 1 1 2 2 2 2 1 0 0]
 [0 0 0 0 0 2 1 2 1 1 0 1 2 0 0]
 [0 0 0 0 0 0 1 2 1 1 1 1 2 0 0]
 [0 0 0 1 1 1 0 1 2 1 1 0 1 2 0]
 [0 0 2 2 1 2 2 0 2 1 1 2 2 0 0]
 [0 0 0 1 2 1 0 0 0 2 2 1 0 0 0]
 [0 0 2 0 1 0 2 2 0 0 1 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [118]:
a, b = map(int, input().split())
_x[a, b] = 1
print(_x)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 2 1 0 0 0 2]
 [0 0 0 0 0 2 1 2 2 2 1 0 0 1 0]
 [0 0 0 0 2 0 1 1 2 1 0 0 2 0 0]
 [0 0 0 0 2 1 2 2 2 1 0 2 1 2 0]
 [0 0 0 0 0 0 1 1 2 2 2 2 1 0 0]
 [0 0 0 0 0 2 1 2 1 1 0 1 2 0 0]
 [0 0 0 0 0 0 1 2 1 1 1 1 2 0 0]
 [0 0 0 1 1 1 0 1 2 1 1 0 1 2 0]
 [0 0 0 2 1 0 2 0 2 1 1 2 2 0 0]
 [0 0 0 1 2 1 0 0 0 2 2 1 0 0 0]
 [0 0 2 0 1 0 2 2 0 0 1 0 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [135]:
_x = \
[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 2],
 [0, 0, 0, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 1, 0],
 [0, 0, 0, 0, 2, 0, 1, 1, 2, 1, 0, 0, 2, 0, 0],
 [0, 0, 0, 0, 2, 1, 2, 2, 2, 1, 0, 2, 1, 2, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 1, 0, 0],
 [0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 0, 1, 2, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 2, 1, 1, 1, 1, 2, 0, 0],
 [0, 0, 0, 1, 1, 1, 0, 1, 2, 1, 1, 0, 1, 2, 0],
 [0, 0, 0, 2, 1, 0, 2, 0, 2, 1, 1, 2, 2, 0, 0],
 [0, 0, 0, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 0, 0],
 [0, 0, 2, 0, 1, 0, 2, 2, 0, 0, 1, 0, 2, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]